version: '3'

services:
  vault:
    image: vault
    cap_add:
      - IPC_LOCK
    ports:
      - 8200:8200
    command: server -dev -dev-listen-address=0.0.0.0:8200 -dev-root-token-id="xDNq4P1jJYF9Gm60GekUh8TW"

  vaultproxy:
    image: openresty/openresty:xenial
    ports:
      - 8089:80    
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
      - "./vault-decode.lua:/etc/nginx/conf.d/lua/vault-decode.lua"
